# Searching 

In [16]:
import numpy as np

var = np.array([4,2,3,4,2,5,2,5,6,7])

x = np.where( var == 2)

print(x)

(array([1, 4, 6]),)


In [17]:
var1 = np.array([1,2,3,4,8,9,10])

x1 = np.searchsorted(var1, [5,6,7], side = "right")

print(x1)

[4 4 4]


# Sort

In [26]:
var_1 = np.array([[4,2,3],[1,10,5],[22,11,6]])

print(np.sort(var_1))

[[ 2  3  4]
 [ 1  5 10]
 [ 6 11 22]]


In [28]:
var_2 = np.array(["a","s","d","f"])

print(np.sort(var_2))

['a' 'd' 'f' 's']


# Filtering array

In [29]:
var_3 = np.array(["a","s","d","f"])

f = [True,False,False,True]

new_a = var_3[f]

print(new_a)

['a' 'f']
