# Insert

In [22]:
import numpy as np

var = np.array([1,2,3,4])

print(var)

# v = np.insert(var, (2,4), 6.5)

x = np.append(var,6.5)

print(x)

[1 2 3 4]
[1.  2.  3.  4.  6.5]


In [23]:
var1 = np.array([[1,2,3],[1,2,3]])

# v1 =  np.insert(var1, 2, [22,23,27], axis = 0)
v1 = np.append(var1,[[45,44,23]],axis = 0)
print(v1)

[[ 1  2  3]
 [ 1  2  3]
 [45 44 23]]


# Delete

In [25]:
import numpy as np

var1 = np.array([1,2,3,4])

print(var1)

d = np.delete(var1,2)

print(d)

[1 2 3 4]
[1 2 4]
