In [4]:
import numpy as np

var = np.array([1,2,3,4,5])

np.random.shuffle(var)

print(var)

[4 2 5 1 3]


# Unique

In [9]:
var1 = np.array([1,2,3,4,2,5,2,6,2,7])

x = np.unique(var1,return_index = True,return_counts = True)

print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 9]), array([1, 4, 1, 1, 1, 1, 1]))


# Resize

In [11]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2, (3,2))

print(y)

[[1 2]
 [3 4]
 [5 6]]


# Flatten

In [22]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2, (3,2))

print(y)
print()
print("Flatten : ",y.flatten(order = "F"))
print("Ravel : ", np.ravel(y,order = "K"))

[[1 2]
 [3 4]
 [5 6]]

Flatten :  [1 3 5 2 4 6]
Ravel :  [1 2 3 4 5 6]
