# Matrix

In [9]:
import numpy as np

var = np.matrix([[1,2],[1,2]])
var2 = np.matrix([[1,2],[1,2]])
print(var)
print()
print(type(var))
print()
print(var * var2)
print()
print(var.dot(var2))

[[1 2]
 [1 2]]

<class 'numpy.matrix'>

[[3 6]
 [3 6]]

[[3 6]
 [3 6]]


In [8]:
var1 = np.array([[1,2,3],[1,2,3]])
print(var1)
print()
print(type(var1))
print()
print(var1*var1)

[[1 2 3]
 [1 2 3]]

<class 'numpy.ndarray'>

[[1 4 9]
 [1 4 9]]
