# slicing

In [11]:
import numpy as np

var = np.array([9,8,7,6,5,4,3])

print(var)

print()

print("2 to 5 : ",var[1:5])
print()

print("2 to end : ",var[1:])
print()

print("Start to 5 : ",var[:5])
print()

print("Stop : ",var[1:5:2])

[9 8 7 6 5 4 3]

2 to 5 :  [8 7 6 5]

2 to end :  [8 7 6 5 4 3]

Start to 5 :  [9 8 7 6 5]

Stop :  [8 6]


In [17]:
var1 = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])

print(var1)
print()

print("2 to 5 : ",var1[0,1:])
print()

print("8 to 5 : ",var1[1,1:])
print()

print("12 to 15 : ",var1[2,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

2 to 5 :  [2 3 4 5]

8 to 5 :  [8 7 6 5]

12 to 15 :  [12 13 14 15]
