In [11]:
import numpy as np

var  =  np.array([4,9,16,4,25,2])

print("min :",np.min(var),np.argmin(var))
print("Max :",np.max(var),np.argmax(var))
print("sqrt :",np.sqrt(var))

min : 2 5
Max : 25 4
sqrt : [2.         3.         4.         2.         5.         1.41421356]


In [12]:
var1 = np.array([[2,1,3],[9,5,6]])

print(np.min(var1,axis = 0))

[2 1 3]


In [15]:
var2 = np.array([1,2,3])
print(np.sin(var2))
print(np.cos(var2))
print(np.cumsum(var2))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]
