# Data Type

In [5]:
import numpy as np

var = np.array([1,2,3,4,12,13,14,15])

print("Data Type :",var.dtype)

Data Type : int64


In [6]:
var = np.array([1.0,1.2,1.3])

print("Data Type :",var.dtype)

Data Type : float64


In [7]:
var = np.array(["A","S","D","F"])

print("Data Type :",var.dtype)

Data Type : <U1


In [8]:
var = np.array(["A","S","D","F",1,2,3,4])

print("Data Type :",var.dtype)

Data Type : <U21


In [13]:
x = np.array([1,2,3,4],dtype = np.int8)

print("Data Type :",x.dtype)
print(x)

Data Type : int8
[1 2 3 4]


In [14]:
x1 = np.array([1,2,3,4],dtype = "f")

print("Data Type :",x1.dtype)
print(x1)

Data Type : float32
[1. 2. 3. 4.]


In [15]:
x2 = np.array([1,2,3,4])

new = np.float32(x)

print("Data Type :",x2.dtype)
print("Data Type :",new.dtype)

print(x2)
print(new)

Data Type : int64
Data Type : float32
[1 2 3 4]
[1. 2. 3. 4.]


In [16]:
x2 = np.array([1,2,3,4])

new = np.float32(x)

new_one =  np.int_(new)

print("Data Type :",x2.dtype)
print("Data Type :",new.dtype)
print("Data Type :",new_one.dtype)

print(x2)
print(new)
print(new_one)

Data Type : int64
Data Type : float32
Data Type : int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [ ]:
x3 = np.array([1,2,3,4])

new_1 =