# ARRAY

In [16]:
import numpy as np

y = np.array([1,2,3,4,5])

print(y)
print(type(y))
print(y.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [15]:
l = []

for i in range(1,5):
    int_1 = int(input("Enter :"))
    l.append(int_1)

print(np.array(l))

Enter : 12
Enter : 13
Enter : 14
Enter : 15


[12 13 14 15]


In [17]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [18]:
ar3 =  np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [20]:
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
