# Shape

In [7]:
import numpy as np

var = np.array([[1,2,3,4],[1,2,3,4]])

print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [11]:
var1 = np.array([1,2,3,4], ndmin=4)
print(var1)
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


In [17]:
var2 = np.array([1,2,3,4,5,6,1,2,3])
print(var2)
print(var2.ndim)
print()
x = var2.reshape(3,3)

print(x)
print(x.ndim)

[1 2 3 4 5 6 1 2 3]
1

[[1 2 3]
 [4 5 6]
 [1 2 3]]
2


In [19]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
print()
x1 = var3.reshape(2,3,2)

print(x1)
print(x1.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [20]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
print()
x1 = var3.reshape(2,3,2)

print(x1)
print(x1.ndim)

print()

one = x1.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
