# Transpose Matrix

In [16]:
import numpy as np

var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()

# Transposr 
print(np.transpose(var))
print()

# sort form
print(var.T)
print()

# swapaxes
print(np.swapaxes(var,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


# Swapaxes Matrix

In [17]:
var2 =  np.matrix([[1,2],[3,4]])
print(var2)
print()
print(np.swapaxes(var2,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


# Inverse Matrix

In [18]:
var3 =  np.matrix([[1,2],[3,4]])
print(var3)
print()

print(np.linalg.inv(var3))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


# Power of matrix

In [22]:
var4 =  np.matrix([[1,2],[3,4]])

print(var4)
print()

print(np.linalg.matrix_power(var4,2))
print()

print(np.linalg.matrix_power(var4,0))
print()

print(np.linalg.matrix_power(var4,-2))
print()

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]



# Determinate Matrix

In [24]:
var5 =  np.matrix([[1,2,3],[3,4,3],[1,2,3]])

print(var5)
print()

print(np.linalg.det(var5))

[[1 2 3]
 [3 4 3]
 [1 2 3]]

0.0
