# Random 

**Rand()**

In [3]:
import numpy as np

var = np.random.rand(4)

print(var)

[0.06604527 0.42293167 0.14270833 0.49274493]


In [4]:
var1 = np.random.rand(2,5)

print(var1)

[[0.40938774 0.31335043 0.74597396 0.7501966  0.28765007]
 [0.1444096  0.56587017 0.92113008 0.48865136 0.45038611]]


**randn()**

In [10]:
var2 = np.random.randn(5)

print(var2)

[-0.43920413  0.43875342  0.15390365 -2.4140757   0.33074367]


**ranf()**

In [13]:
var3 = np.random.ranf(4)

print(var3)

[0.21224016 0.4427783  0.9306313  0.0797573 ]


**randint()**

In [15]:
var4 = np.random.randint(5,20,5)

print(var4)

[18  5 15 13  7]
