# indexing

In [5]:
import numpy as np

var = np.array([9,8,7,6])


print(var[1])
print(var[-3])

8
8


In [10]:
var1 = np.array([[9,8,7],[4,5,6]])

print(var1)
print(var1.ndim)
print()

print(var1[0,2])

[[9 8 7]
 [4 5 6]]
2

7


In [14]:
var2 = np.array([[[1,2],[6,7]]])

print(var2)
print(var2.ndim)
print()
print(var2[0,1,1])

[[[1 2]
  [6 7]]]
3

7
